!!com.taro.backspring.Configuration
backupStrategyType: MOCK
filter:
  excludes: ['.gvfs/']
  includes: ['*']
name: My Configuration
schedule: 30 * * * * ?
runNow: false
sourceDirectory: /home/foo
targetDirectory: /media/backup
logging: FALSE
