!!com.taro.backspring.Configuration
backupStrategyType: RSYNC
filter:
  excludes: ['.gvfs', '.kde', '.cache', 'Downloads', '.adobe', '.local', '.m2' ]
name: My Configuration
schedule: 0 30 21 * * ?
runNow: TRUE
sourceDirectory: /home/foo
targetDirectory: /media/Backup
logging: TRUE
